
# https://docs.travis-ci.com/user/languages/android/#CI-Environment-for-Android-Projects

language: android
jdk: oraclejdk8

# get more ram: https://docs.travis-ci.com/user/ci-environment/
sudo: required

env:
  global:
    - ANDROID_TARGET=android-22 # version in emulator
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - ${ANDROID_TARGET}
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

# running emulator
# https://docs.travis-ci.com/user/languages/android#How-to-Create-and-Start-an-Emulator
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -noaudio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew build testConnectedCheck

# https://docs.travis-ci.com/user/languages/android/#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/