
# https://docs.travis-ci.com/user/languages/android/#CI-Environment-for-Android-Projects

language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24

# I don't use emulator yet
script: ./gradlew build

# https://docs.travis-ci.com/user/languages/android/#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/